apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: default
spec:
  serviceName: app
  replicas: 3
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: app
          image: app:1.0
          env:
            - name: NUM_REPLICAS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: replicas
          command: ["python3"]
          args: ["app.py", "3"]