# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='erb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\terb.proto\"3\n\x08Hearbeat\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62ytes\x18\x03 \x01(\x0c\"\x1b\n\rHearbeatReply\x12\n\n\x02id\x18\x01 \x01(\r26\n\tHeartbeat\x12)\n\x0cSendHearbeat\x12\t.Hearbeat\x1a\x0e.HearbeatReplyb\x06proto3'
)




_HEARBEAT = _descriptor.Descriptor(
  name='Hearbeat',
  full_name='Hearbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Hearbeat.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Hearbeat.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='Hearbeat.bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=64,
)


_HEARBEATREPLY = _descriptor.Descriptor(
  name='HearbeatReply',
  full_name='HearbeatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='HearbeatReply.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['Hearbeat'] = _HEARBEAT
DESCRIPTOR.message_types_by_name['HearbeatReply'] = _HEARBEATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hearbeat = _reflection.GeneratedProtocolMessageType('Hearbeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARBEAT,
  '__module__' : 'erb_pb2'
  # @@protoc_insertion_point(class_scope:Hearbeat)
  })
_sym_db.RegisterMessage(Hearbeat)

HearbeatReply = _reflection.GeneratedProtocolMessageType('HearbeatReply', (_message.Message,), {
  'DESCRIPTOR' : _HEARBEATREPLY,
  '__module__' : 'erb_pb2'
  # @@protoc_insertion_point(class_scope:HearbeatReply)
  })
_sym_db.RegisterMessage(HearbeatReply)



_HEARTBEAT = _descriptor.ServiceDescriptor(
  name='Heartbeat',
  full_name='Heartbeat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=95,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendHearbeat',
    full_name='Heartbeat.SendHearbeat',
    index=0,
    containing_service=None,
    input_type=_HEARBEAT,
    output_type=_HEARBEATREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEARTBEAT)

DESCRIPTOR.services_by_name['Heartbeat'] = _HEARTBEAT

# @@protoc_insertion_point(module_scope)
