# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='erb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\terb.proto\"\n\n\x08Hearbeat\"\x0f\n\rHearbeatReply26\n\tHeartbeat\x12)\n\x0cSendHearbeat\x12\t.Hearbeat\x1a\x0e.HearbeatReplyb\x06proto3'
)




_HEARBEAT = _descriptor.Descriptor(
  name='Hearbeat',
  full_name='Hearbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=23,
)


_HEARBEATREPLY = _descriptor.Descriptor(
  name='HearbeatReply',
  full_name='HearbeatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['Hearbeat'] = _HEARBEAT
DESCRIPTOR.message_types_by_name['HearbeatReply'] = _HEARBEATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hearbeat = _reflection.GeneratedProtocolMessageType('Hearbeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARBEAT,
  '__module__' : 'erb_pb2'
  # @@protoc_insertion_point(class_scope:Hearbeat)
  })
_sym_db.RegisterMessage(Hearbeat)

HearbeatReply = _reflection.GeneratedProtocolMessageType('HearbeatReply', (_message.Message,), {
  'DESCRIPTOR' : _HEARBEATREPLY,
  '__module__' : 'erb_pb2'
  # @@protoc_insertion_point(class_scope:HearbeatReply)
  })
_sym_db.RegisterMessage(HearbeatReply)



_HEARTBEAT = _descriptor.ServiceDescriptor(
  name='Heartbeat',
  full_name='Heartbeat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=42,
  serialized_end=96,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendHearbeat',
    full_name='Heartbeat.SendHearbeat',
    index=0,
    containing_service=None,
    input_type=_HEARBEAT,
    output_type=_HEARBEATREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEARTBEAT)

DESCRIPTOR.services_by_name['Heartbeat'] = _HEARTBEAT

# @@protoc_insertion_point(module_scope)
