apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  selector:
    app: app-service
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  serviceName: app-service
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-config
          image: init-config:1.0
          volumeMounts:
            - name: configdir
              mountPath: "/var/config"
          command: ["echo"]
          args: ["xyz", ">", "network.conf"]
      containers:
        - name: app
          image: app:1.0
          volumeMounts:
            - name: configdir
              mountPath: "/var/config"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["python3"]
          args: ["app.py", "3", "$(POD_IP)", "default"]
        - name: haproxy
          image: app-haproxy:1.0
        - name: app-proxy
          image: app-proxy:1.0
          args: ["3", "default"]
      volumes:
        - name: configdir
          emptyDir: {}