apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    <filter kubernetes.var.log.containers.app**.log>
      @type record_transformer
      enable_ruby true
      <record>
        timestamp ${t = Time.now; (((t.to_i * 1000000000) + t.nsec) / 1000000).to_s}
      </record>
    </filter>

    <match kubernetes.var.log.containers.app**_app**.log>
      @type copy

      <store>
        @type stdout
      </store>

      <store>
        @type http

        endpoint http://log-service:3000/api/logging/app
        open_timeout 2

        <format>
          @type json
        </format>
        
        <buffer>
          flush_thread_count 8
          flush_interval 1s
        </buffer>
      </store>
    </match>

    <match kubernetes.var.log.containers.app**_goproxy**.log>
      @type copy

      <store>
        @type stdout
      </store>

      <store>
        @type http

        endpoint http://log-service:3000/api/logging/proxy
        open_timeout 2

        <format>
          @type json
        </format>
        
        <buffer>
          flush_thread_count 8
          flush_interval 1s
        </buffer>
      </store>
    </match>