apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: frontend-service
  template:
    metadata:
      labels:
        deploy: frontend-service
        run: frontend-service
    spec:
      containers:
        - name: frontend-server
          image: frontend-server:1.0
          ports:
          - containerPort: 80
