apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  ports:
    - name: logs
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: ws
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    run: log-service