apiVersion: v1
kind: Service
metadata:
  name: log-frontend-service
spec:
  ports:
    - name: logs
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    run: log-frontend-service