# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chord.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x63hord.proto\"7\n\rPutKeyRequest\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\x12\x13\n\x03val\x18\x02 \x01(\x0b\x32\x06.Value\"\x10\n\x0ePutKeyResponse\"\"\n\rGetKeyRequest\x12\x11\n\x03key\x18\x01 \x01(\x0b\x32\x04.Key\"%\n\x0eGetKeyResponse\x12\x13\n\x03val\x18\x01 \x01(\x0b\x32\x06.Value\"\x1e\n\x04Node\x12\n\n\x02ip\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"\x11\n\x03Key\x12\n\n\x02id\x18\x01 \x01(\r\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty2\xcd\x01\n\x05\x43hord\x12)\n\x06PutKey\x12\x0e.PutKeyRequest\x1a\x0f.PutKeyResponse\x12)\n\x06GetKey\x12\x0e.GetKeyRequest\x1a\x0f.GetKeyResponse\x12\x16\n\x04Ping\x12\x06.Empty\x1a\x06.Empty\x12\x1c\n\rFindSuccessor\x12\x04.Key\x1a\x05.Node\x12\x17\n\x06Notify\x12\x05.Node\x1a\x06.Empty\x12\x1f\n\x0eGetPredecessor\x12\x06.Empty\x1a\x05.Nodeb\x06proto3'
)




_PUTKEYREQUEST = _descriptor.Descriptor(
  name='PutKeyRequest',
  full_name='PutKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PutKeyRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='PutKeyRequest.val', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=70,
)


_PUTKEYRESPONSE = _descriptor.Descriptor(
  name='PutKeyResponse',
  full_name='PutKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=88,
)


_GETKEYREQUEST = _descriptor.Descriptor(
  name='GetKeyRequest',
  full_name='GetKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GetKeyRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=124,
)


_GETKEYRESPONSE = _descriptor.Descriptor(
  name='GetKeyResponse',
  full_name='GetKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='GetKeyResponse.val', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=163,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='Node.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Node.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=195,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Key.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=214,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Value.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=238,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=247,
)

_PUTKEYREQUEST.fields_by_name['key'].message_type = _KEY
_PUTKEYREQUEST.fields_by_name['val'].message_type = _VALUE
_GETKEYREQUEST.fields_by_name['key'].message_type = _KEY
_GETKEYRESPONSE.fields_by_name['val'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['PutKeyRequest'] = _PUTKEYREQUEST
DESCRIPTOR.message_types_by_name['PutKeyResponse'] = _PUTKEYRESPONSE
DESCRIPTOR.message_types_by_name['GetKeyRequest'] = _GETKEYREQUEST
DESCRIPTOR.message_types_by_name['GetKeyResponse'] = _GETKEYRESPONSE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutKeyRequest = _reflection.GeneratedProtocolMessageType('PutKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTKEYREQUEST,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:PutKeyRequest)
  })
_sym_db.RegisterMessage(PutKeyRequest)

PutKeyResponse = _reflection.GeneratedProtocolMessageType('PutKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUTKEYRESPONSE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:PutKeyResponse)
  })
_sym_db.RegisterMessage(PutKeyResponse)

GetKeyRequest = _reflection.GeneratedProtocolMessageType('GetKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYREQUEST,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:GetKeyRequest)
  })
_sym_db.RegisterMessage(GetKeyRequest)

GetKeyResponse = _reflection.GeneratedProtocolMessageType('GetKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYRESPONSE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:GetKeyResponse)
  })
_sym_db.RegisterMessage(GetKeyResponse)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Node)
  })
_sym_db.RegisterMessage(Node)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Key)
  })
_sym_db.RegisterMessage(Key)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  })
_sym_db.RegisterMessage(Value)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_CHORD = _descriptor.ServiceDescriptor(
  name='Chord',
  full_name='Chord',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=250,
  serialized_end=455,
  methods=[
  _descriptor.MethodDescriptor(
    name='PutKey',
    full_name='Chord.PutKey',
    index=0,
    containing_service=None,
    input_type=_PUTKEYREQUEST,
    output_type=_PUTKEYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetKey',
    full_name='Chord.GetKey',
    index=1,
    containing_service=None,
    input_type=_GETKEYREQUEST,
    output_type=_GETKEYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='Chord.Ping',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindSuccessor',
    full_name='Chord.FindSuccessor',
    index=3,
    containing_service=None,
    input_type=_KEY,
    output_type=_NODE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Notify',
    full_name='Chord.Notify',
    index=4,
    containing_service=None,
    input_type=_NODE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPredecessor',
    full_name='Chord.GetPredecessor',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NODE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHORD)

DESCRIPTOR.services_by_name['Chord'] = _CHORD

# @@protoc_insertion_point(module_scope)
