# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import erb_pb2 as erb__pb2


class HeartbeatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendHearbeat = channel.unary_unary(
        '/Heartbeat/SendHearbeat',
        request_serializer=erb__pb2.Hearbeat.SerializeToString,
        response_deserializer=erb__pb2.HearbeatReply.FromString,
        )


class HeartbeatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendHearbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HeartbeatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendHearbeat': grpc.unary_unary_rpc_method_handler(
          servicer.SendHearbeat,
          request_deserializer=erb__pb2.Hearbeat.FromString,
          response_serializer=erb__pb2.HearbeatReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Heartbeat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
