apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    run: log-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: log-service
  template:
    metadata:
      labels:
        deploy: log-service
        run: log-service
    spec:
      containers:
        - name: log-server
          image: log-server:1.0
          ports:
          - containerPort: 3000
