apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  serviceName: app-service
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: app
          image: app:1.0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["python3"]
          args: ["app.py", "3", "$(POD_IP)"]